variable "environment" {
  description = "Environment name"
  type        = string
  default     = "test"
}

variable "aws_region" {
  description = "AWS region to deploy resources"
  type        = string
  default     = "us-east-1"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC"
  type        = string
  default     = "10.0.0.0/16"
}

variable "availability_zones" {
  description = "List of availability zones to use"
  type        = list(string)
  default     = ["us-east-1a", "us-east-1b"]
}

variable "db_password" {
  description = "Password for MongoDB database"
  type        = string
  sensitive   = true
}

variable "jwt_secret" {
  description = "Secret key for JWT token generation"
  type        = string
  sensitive   = true
}

variable "backend_container_tag" {
  description = "Tag for the backend container image"
  type        = string
  default     = "latest"
}

variable "frontend_container_tag" {
  description = "Tag for the frontend container image"
  type        = string
  default     = "latest"
}

# ECR repository URL is now generated by the ECR module