name: SpearPoint CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Node Dependencies
        run: npm ci
      
      - name: Run Frontend Linting
        run: cd packages/dashboard/frontend && npm run lint
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Python Dependencies
        run: |
          cd packages/dashboard/backend-python
          pip install flake8
          pip install -r requirements.txt
      
      - name: Run Python Linting
        run: |
          cd packages/dashboard/backend-python
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Node Dependencies
        run: cd packages/dashboard/frontend && npm ci
      
      - name: Run Frontend Tests
        run: cd packages/dashboard/frontend && npm test
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Python Dependencies
        run: |
          cd packages/dashboard/backend-python
          pip install pytest
          pip install -r requirements.txt
      
      - name: Run Python Tests
        run: |
          cd packages/dashboard/backend-python
          pytest
        env:
          DATABASE_URL: mongodb://localhost:27017/spearpoint_test
          JWT_SECRET: test_secret_key

  build:
    name: Build Packages
    runs-on: ubuntu-latest
    needs: [lint, test]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Core Dependencies
        run: cd packages/core && npm ci
      
      - name: Build Core Package
        run: cd packages/core && npm run build
      
      - name: Build Frontend
        run: |
          cd packages/dashboard/frontend
          npm ci
          npm run build